import type { Dispatch, SetStateAction } from 'react';
import type { User } from '@/types';
import type { SortKey } from '@/features/mentor/marketplace/mentorMarketplace.constants';

export type MentorMarketplaceViewModel = {
  loading: boolean;
  error: string | null;
  searchTerm: string;
  setSearchTerm: Dispatch<SetStateAction<string>>;
  verifiedOnly: boolean;
  setVerifiedOnly: Dispatch<SetStateAction<boolean>>;
  maxPrice: number;
  setMaxPrice: Dispatch<SetStateAction<number>>;
  minRating: number;
  setMinRating: Dispatch<SetStateAction<number>>;
  minSessions: number;
  setMinSessions: Dispatch<SetStateAction<number>>;
  sortBy: SortKey;
  setSortBy: Dispatch<SetStateAction<SortKey>>;
  showMobileFilters: boolean;
  setShowMobileFilters: Dispatch<SetStateAction<boolean>>;
  allCategories: string[];
  allSkills: string[];
  allUniversities: string[];
  allMajors: string[];
  allYears: number[];
  priceBounds: { min: number; max: number };
  filtered: User[];
  selectedCategories: string[];
  selectedSkills: string[];
  selectedUniversities: string[];
  selectedMajors: string[];
  selectedYears: number[];
  toggleCategory: (cat: string) => void;
  toggleSkill: (skill: string) => void;
  toggleUniversity: (u: string) => void;
  toggleMajor: (m: string) => void;
  toggleYear: (y: number) => void;
  clearFilters: () => void;
  activeFilterCount: number;
  retry: () => void;
};
